name = "EFEasVFE"
uuid = "bd59a8c5-9db7-47e6-b88a-465bf09f9b5b"
authors = ["wouterwln"]
version = "0.0.1"

[deps]
ArgParse = "c7e460c6-2fb9-53a9-8c5b-16f535851c63"
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
DrWatson = "634d3b9d-ee7a-5ddf-bec9-22491ea816e1"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
ImageCore = "a09fc81d-aa75-5fe9-8630-4744c3626534"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LogExpFunctions = "2ab3a3ac-af41-5b50-aa03-7779005ae688"
LoggingExtras = "e6f89c97-d47a-5376-807f-9c37f3926c36"
LoopVectorization = "bdcacae8-1622-11e9-2a5c-532679323890"
NPZ = "15e1cf62-19b3-5cfa-8e77-841668bca605"
PGFPlotsX = "8314cec4-20b6-5062-9cdb-752b83310925"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
ReactiveMP = "a194aa59-28ba-4574-a09c-4a745416d6e3"
RxInfer = "86711068-29c9-4ff7-b620-ae75d7495b3d"
StableRNGs = "860ef19b-820b-49d6-a774-d7a799459cd3"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
TensorOperations = "6aa20fa7-93e2-5fca-9bc0-fbd0db3c71a2"
TinyHugeNumbers = "783c9a47-75a3-44ac-a16b-f1ab7b3acf04"
Tullio = "bc48ee85-29a4-5162-ae0b-a64e1601d4bc"
UUIDs = "cf7118a7-6976-5b1a-9a39-7adc72f591a4"
VideoIO = "d6d074c3-1acf-5d4c-9a43-ef38773959a2"

[compat]
ArgParse = "1.2.0"
Colors = "0.13.0"
Distributions = "0.25.119"
DrWatson = "2.18.0"
FileIO = "1.17.0"
HTTP = "1.10.16"
ImageCore = "0.10.5"
JLD2 = "0.5.13"
JSON = "0.21.4"
LogExpFunctions = "0.3.29"
LoggingExtras = "1.1.0"
LoopVectorization = "0.12.172"
NPZ = "0.4.3"
PGFPlotsX = "1.6.2"
Plots = "1.40.13"
ProgressMeter = "1.10.4"
ReactiveMP = "5.4.3"
RxInfer = "4.4.2"
StableRNGs = "1.0.2"
StaticArrays = "1.9.13"
TensorOperations = "5.2.0"
TinyHugeNumbers = "1.0.2"
Tullio = "0.3.8"
VideoIO = "1.1.1"
LinearAlgebra = "1.11.0"
UUIDs = "1.11.0"
julia = "1.10"

[extras]
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
ReTestItems = "817f1d60-ba6b-4fd5-9520-3cf149f6a823"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Random", "ReTestItems"]
